apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      creationTimestamp: "2024-01-27T18:49:18Z"
      labels:
        app: jupyter-app
      name: jupyter-svc
      namespace: jupyter
      resourceVersion: "2706"
      uid: a3da1a3e-6ef2-4de1-8037-0b7a219e8440
    spec:
      clusterIP: 10.103.235.7
      clusterIPs:
        - 10.103.235.7
      externalTrafficPolicy: Cluster
      internalTrafficPolicy: Cluster
      ipFamilies:
        - IPv4
      ipFamilyPolicy: SingleStack
      ports:
        - nodePort: 30000
          port: 8888
          protocol: TCP
          targetPort: 8888
      selector:
        app: jupyter-pods
      sessionAffinity: None
      type: NodePort
    status:
      loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
